PYTHONPATH=./ python src/sae_reconstruction/train_sae.py \
    --seed 42 \
    --use_wandb False \
    --wandb_project sae_training \
    --metadata_path data/metadata.csv \
    --embedding_dir data/embeddings \
    --domain_list domain1,domain2 \
    --embedding_dim 768 \
    --expansion_factor 5 \
    --learning_rate 1e-4 \
    --max_epochs 50 \
    --patience 5 \
    --batch_size 32 \
    --batch_size_val 32 \
    --num_workers 0 \
    --pin_memory True \
    --weight_decay 1e-2 \
    --l1_weight 1e-3
